### ISSUE TITLE
Intification is broken for integers between 2^63 and 2^64 - 1

### ISSUE THREAD

**Issue by trizen** [turnstep/Math-GMP#2]
Hello! As pointed out in https://github.com/danaj/Math-Prime-Util/issues/20, the intification of Math::GMP seems to return incorrect values for integers between 2^63 and 2^64 - 1.

Example:

```perl
use 5.010;
use Math::GMP;

my $n = 9223372036854775828;     # 2^63 + 20
my $z = Math::GMP->new($n);

say $n;             #=> 9223372036854775828
say $z;             #=> 9223372036854775828

say int($n);        #=> 9223372036854775828
say int($z);        #=> 20 (incorrect)
```

Would be very nice if this can be fixed.

Thanks for your work,
Trizen

**Comment by shlomif** [comment]
On Sat, 07 Apr 2018 15:48:31 +0000 (UTC)
Daniel Șuteu <notifications@github.com> wrote:

> Hello! As pointed out in https://github.com/danaj/Math-Prime-Util/issues/20,
> the intification of Math::GMP seems to return incorrect values for integers
> between 2^63 and 2^64 - 1.
> 
> Example:
> 
> ```perl
> use 5.010;
> use Math::GMP;
> 
> my $n = 9223372036854775828;     # 2^63 + 20
> my $z = Math::GMP->new($n);
> 
> say $n;             #=> 9223372036854775828
> say $z;             #=> 9223372036854775828
> 
> say int($n);        #=> 9223372036854775828
> say int($z);        #=> 20 (incorrect)
> ```
> 
> Would be very nice if this can be fixed.
> 

acknowledged. pull-reqs are welcome. Should not int($z) just return $z?

> Thanks for your work,
> Trizen
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://youtu.be/xZLwtc9x4yA - Anime in Real Life!! (Parody)

There is no IGLU Cabal! None of them could pass the Turing test. But strangely
enough a computer program they coded, could.
    — http://www.shlomifish.org/humour/fortunes/shlomif.html

Please reply to list if it's a mailing list post - http://shlom.in/reply .
