### ISSUE TITLE
build from git

### ISSUE THREAD

**Issue by hvds** [turnstep/Math-GMP#4]
Hi, I am working with the git repo because I want to add some new functionality to Math::GMP, but there's no Makefile.PL and no info in README or in INSTALL how you might do that. I assume the dist.ini is something to do with it, but I'm also not seeing any clues there.

A link to an appropriate manpage would be welcome.

**Comment by shlomif** [comment]
See http://dzil.org/ and https://perl-begin.org/topics/cpan/ and https://metacpan.org/pod/Dist::Zilla . I'll try to document it. Thanks!

**Comment by shlomif** [comment]
Closing as fixed.
