### ISSUE TITLE
MALFORMED Signature file for 2.21

### ISSUE THREAD

**Issue by lemrouch** [turnstep/Math-GMP#6]
Hi,
I got _==> MALFORMED Signature file! <==_ from _cpansign -v_
This makes sense as the _SIGNATURE_'s last line is
`SHA256 dc5efc57dfb75d237226e738436163cf52c61d724e2dc595d97d7b95a1196352 xt/release/trailing-space.t`
Would you regenerate the file please?

**Comment by shlomif** [comment]
@lemrouch : thanks for the report: https://github.com/turnstep/Math-GMP/blob/3c5887d540d7e4b89b84b0f5740970ee94b33aba/Changes#L3 - i decided to axe it in v2.22.

**Comment by shlomif** [comment]
Closing for now as FIXED-ish
